---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: launched
  remote_user: root
  sudo: yes
  gather_facts: True
  roles:
    - common
    - db
    - web

# - name: configure and deploy the webservers and application code
#   hosts: webservers
#   remote_user: root
#   roles:
#     - web
#
# - name: deploy MySQL and configure the databases
#   hosts: dbservers
#   remote_user: root
#   roles:
#     - db