---
- name: install haproxy
  yum: name=haproxy state=installed

- name: Open firewall port for haproxy.
  # lineinfile: dest=/etc/sysconfig/iptables state=present regexp="$listenport" insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport $listenport -j  ACCEPT"
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ listenport }}" insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ listenport }} -j  ACCEPT"
  notify: restart iptables

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy
